id: P010315
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 20:43:39.758962
source_metadata:
  id: bdr:W1KG10421
  title: ལེགས་བཤད་སྙིང་པོའི་མཆན་འགྲེལ།
  author: ''
  volumes:
    49a57b73b8cc450aa9902450e52217d2:
      image_group_id: I1KG10425
      title: ''
      volume_number: 1
      total_pages: 583
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
